config/routes.rb
Rails.application.routes.draw do
  
  root to: 'messages#index'

  get 'ABOUT',to:'abouts#index'

  get 'PORTFOLIO',to:'portfolios#index'
  
  resources :messages
  resources :abouts, only: [:index]
  resources :portfolios, only: [:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
    
    def index
    
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController

  #Informationモデルのレコードの一覧表示
  #Information.allで全てのレコードを取得して、インスタンス変数の@informationに代入している
  def index
    @informations = Information.all.page(params[:page]).per(5).order(id: :desc)
  end

  #個別表示
  def show
    set_information
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    
    if @information.save
      flash[:success] = '更新履歴が投稿されました'
      redirect_to @information
    else
      flash.now[:danger] = '投稿できませんでした'
      render :new
    end
  end

  def edit
    set_information
  end

  def update
    set_information
    if @information.update(information_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @information
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end

  def destroy
    set_information
    @information.destroy
    
    flash[:success] = 'タスクは削除されました'
    redirect_to informations_url
  end

  
  
  
  private
  
  def set_information
    @information = Information.find(params[:id])
  end
  
  # Strong Parameter
  def information_params
    params.require(:information).permit(:title, :content)
  end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  #Messageモデルのレコードの一覧表示
  #Message.allで全てのレコードを取得して、インスタンス変数の@informationに代入している
  def index
    @messages = Message.all.page(params[:page]).per(5).order(id: :desc)
  end

  #個別表示
  def show
    set_information
  end

  def new
    @message = Message.new
    @messages = Message.all.page(params[:page]).order(id: :desc)
  end

  def create
    @message = Message.new(message_params)
    
    if @message.save
      flash[:success] = '更新履歴が投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = '投稿できませんでした'
      render :new
    end
  end

  def edit
    set_information
  end

  def update
    set_information
    if @message.update(message_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @message
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end

  def destroy
    set_information
    @message.destroy
    
    flash[:success] = 'タスクは削除されました'
    redirect_to messages_url
  end

  
  
  
  private
  
  def set_information
    @message = Message.find(params[:id])
  end
  
  # Strong Parameter
  def message_params
    params.require(:message).permit(:title, :content)
  end
 
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    
    def index
    
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abouts/index.html.erb
  <div class="row skill justify-content-center">
    <div class="col-md-3">
      <img src="assets/me001.png" alt="me image">
      <br/><br/>
      <h6>西坂 麻衣  (Nishisaka Mai)</h6>
      <br/>
      <p class="me">生年月日：１９９２年９月</p>
      <p class="me">年齢：２７歳</p>
      <p class="me">血液型：Ａ型</p>
      <p class="me">趣味：ゲーム、映画鑑賞</p>
    </div>
    
      <div class="col-md-2">
            <div class="card" style="width:90%">  
              <img class="card-img-top" src="assets/htmlcss.png" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">HTML/CSS</h5>
                <p class="card-text">独学で勉強していました。Tech Academyというオンラインスクールにて、Webアプリケーションコースのカリキュラム内でも少し学びました。</p>
              </div>
            </div>
      </div>
      <div class="col-md-2">
            <div class="card" style="width:90%">
              <img class="card-img-top" src="assets/bootstrap.png" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">Bootstrap</h5>
                <p class="card-text">独学で勉強していました。Tech Academyというオンラインスクールにて、Webアプリケーションコースのカリキュラムで学びました。</p>
              </div>
            </div>
      </div>
      <div class="col-md-2">
            <div class="card" style="width:90%">
              <img class="card-img-top" src="assets/ruby.png" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">Ruby</h5>
                <p class="card-text">Tech Academyというオンラインスクールにて、Webアプリケーションコースのカリキュラムで学びました。使用したDBMSはMySQLです。</p>
              </div>
            </div>
      </div>
  </div>

  <div class="container-full bottomliner02">
  </div>

app/views/layouts/_flash_messages.html.erb
  
<% flash.each do |message_type, message| %>

  <div>
    <%= message %>      
  </div>
  
  <% end %>

app/views/layouts/_navbar.html.erb
<div class="container-full fixed-top">
  <nav class="navbar navbar-expand-sm p-1">
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブナビゲーション"><!--  button type="button"()  .navbar-toggler()  .ml-auto()  .data-toggle="collapse"(折り畳み機能) .data-target="#navbar"(ターゲットを示す) .aria-controls="Navbar"(対象を示す) .aria-expanded="false"(開閉状態)  .aria-label="?"() -->
        <span class="navbar-toggler-icon"></span><!--  .navbar-toggler-icon(トグルアイコン)  .bg-(背景色)  -->
    </button>
    <div class="collapse navbar-collapse" id="Navber">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0"><!--  .navbar-nav(ドロップダウンのサポート)  .ml-(マージンレフト)  .mt-lg-(マージントップーlg以上)  -->
           <li class="nav-item nav-text"><%= link_to 'TOP', root_path, class:'nav-link' %></li>
           <li class="nav-item nav-text"><%= link_to 'ABOUT', abouts_path, class:'nav-link' %></li>
           <li class="nav-item nav-text"><%= link_to 'PORTFOLIO', portfolios_path, class:'nav-link' %></li>
           <li class="nav-item nav-text"><%= link_to 'GitHub', 'https://github.com/24mai', class:'nav-link' %></li>
           <li class="nav-item nav-text"><%= link_to 'EVERNOTE', 'https://www.evernote.com/shard/s393/sh/e1253ff5-3797-4906-b59f-6169f522b91a/7e4d76f3fa6b9918c6484a5cdf06dd61', class:'nav-link' %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--　文字コードの指定　-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--　Bootstrap CSS　-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <!--  上書き CSS  -->
    <link rel="stylesheet" type="text/css" href="application.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <header>
        <!--  社名ロゴ画像・営業時間  -->
    <div class="container-fluid fixed-top bg-white">
      <div class="row title-top">
        <div class="col-12 col-md-8">
            <img src="assets/24saka_top.png">
        </div>
        <div class="col-12 col-md-4">
        
        </div>
      </div>
    </div>
    
    <%= render 'layouts/navbar' %>
  </header>
  
  <body>
    <%= render 'layouts/flash_messages' %>
    <dev class="container yield-setting">
    <%= yield %>
    </div>
  </body>
  
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-10">
    <%= form_with(model: message, local: true) do |f| %>
      <% if message.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul>
            <% message.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, '更新内容' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="row form justify-content-center">
  <div class="col-md-6">

    <h3>id: 
    <%= @message.id %>
     のメッセージ編集ページ</h3>
     <br/>
    
    <%= render 'form', message: @message %>
    
    <br/>
    <%= link_to 'TOPに戻る', messages_path %>
  </div>
</div>

app/views/messages/index.html.erb
  <div class="row top-row justify-content-center">
    <div class="col-md-6">
        <div class="news overflow-auto">
              <% @messages.each do |message| %>
                <p class="title"><%=message.title %></p>
                <p class="content"><%= message.content %></p>
                <p class="content">（更新日時:　<%= message.created_at.to_s %>）</p>
                <br/>
              <% end %>
              <br/>
              <p class="write">
                 <%= link_to image_tag('/assets/write.png', { :border => '0', :alt => '新規'}), new_message_path %>
              </p>
        </div>
    </div>
    <div class="col-md-3">
        <br/>
        <br/>
      　<div class="container-fluid">
        　<a class="twitter-timeline" data-width=fluid data-height="400" data-theme="light" data-link-color="#FAB81E" href="https://twitter.com/allntmr?ref_src=twsrc%5Etfw">Tweets by allntmr</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      　</div>
    </div> 
  </div>

  <div class="container-full">
    <div class="row bottomliner01">
    </div>
  </div>

app/views/messages/new.html.erb
<div class="row form justify-content-center">
  <div class="col-md-5">
    <h3>更新履歴　投稿フォーム</h3>
    </br>
    </br>
    <%= render 'form', message: @message %>
    <br/>
    <%= link_to 'TOPに戻る', messages_path %>
  </div>
  <div class="col-md-5">
    <h3>投稿一覧</h3>
    <div class="news overflow-auto">
    <% @messages.each do |message| %>
      <p class="title"><%=link_to message.title, message %></p>
      <p class="content"><%= message.content %></p>
      <p class="content">（更新日時:　<%= message.created_at.to_s %>）</p>
      <br/>
    <% end %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row form justify-content-center">
  <div class="col-md-6">

    <h3><%= @message.title %>の詳細ページ</h3>
    <br/><br/>
    <p>
        タイトル   ：<%= @message.title %><br/>
        更新内容  ：<%= @message.content %>
    </p>
    <br/><br/> 
    
    <%= link_to 'この内容を編集する', edit_message_path(@message) %>
    <br/>
    <%= link_to 'この内容を削除する', @message, method: :delete, data:{confirm: '削除しますか？' } %>
    <br/>
    <%= link_to 'TOPに戻る', messages_path %>
  </div>
</div>

app/views/portfolios/index.html.erb
  <div class="row portfolio justify-content-center">
    <div class="col-md-8">
      
    <div class="list overflow-auto">  
    <ul class="list-unstyled" style="width:850px">
      <li class="media mb-5">
        <img class="img" src="assets/form.png" width="300" height="200" alt="1">
        <div class="media-body">
        <h5>準備中</h5>
            こちらのポートフォリオは準備中です。
        </div>
      </li>
      <li class="media mb-5">
        <img class="img" border="1" src="assets/form.png" width="300" height="200" alt="1">
        <div class="media-body">
        <h5>準備中</h5>
            こちらのポートフォリオは準備中です。
        </div>
      </li>
    </ul>
    </div> 
      
    </div>
  </div>
  
    <div class="container-full bottomliner03">
   </div>